name: museo_zuccante
description: School project for the ITIS Zuccante Museum.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice: any
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  dio_log: ^1.3.5
  easy_localization: any
  equatable: ^2.0.0
  f_logs: ^1.2.2
  fancy_shimmer_image: ^1.2.0
  floor: ^0.18.0
  flutter_bloc: ^6.1.3
  flutter_email_sender: ^5.0.0
  flutter_markdown: any
  flutter_neumorphic: ^3.1.0
  get_it: ^6.0.0
  google_fonts: any
  permission_handler: null
  qr_code_scanner: ^0.3.5
  rxdart: ^0.25.0
  shared_preferences: null
  shimmer: ^1.1.2
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  floor_generator: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/map/
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 200

        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
