name: museo_zuccante
description: School project for the ITIS Zuccante Museum.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alice: ^0.1.5
  connectivity: ^0.4.9+3
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  dio: ^3.0.10
  dio_log: ^1.3.5
  easy_localization: ^2.3.3
  equatable: ^1.2.5
  f_logs: ^1.2.2
  fancy_shimmer_image: ^1.2.0
  floor: ^0.14.0
  flutter_bloc: ^6.0.6
  flutter_email_sender: ^3.0.1
  flutter_markdown: ^0.4.4
  flutter_neumorphic: ^3.0.3
  get_it: ^5.0.1
  google_fonts: ^1.1.0
  permission_handler: ^5.0.1+1
  qr_code_scanner: ^0.0.13
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12
  shimmer: ^1.1.1
  stack_trace: ^1.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  floor_generator: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 200

        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
